### ISSUE TITLE
Add RSS

### ISSUE THREAD

**Issue by ylecuyer** [shonumi/shonumi.github.io#1]
Please add rss to the nds emulator series

**Comment by Candunc** [comment]
You can likely watch the repository and get updates (new commits likely means new articles) that way.

By the looks of how the website is set up, there may not be an automatic way to generate an RSS feed, and maintaining it manually is likely a lot of work for a small convenience to you.

**Comment by fox8091** [comment]
Was this intentionally left closed or is that just from forgetting about it after GitHub closed the issue?
